// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_M8VyK_4u0i-gRKx6l96za1XBp2cJzPk',
    appId: '1:1051279993075:web:bdbf700217df94d7c8af86',
    messagingSenderId: '1051279993075',
    projectId: 'expensedaily-3582e',
    authDomain: 'expensedaily-3582e.firebaseapp.com',
    storageBucket: 'expensedaily-3582e.firebasestorage.app',
    measurementId: 'G-BW31MTRMN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhkWQ_-1soV6lm8jZykYmw2CMGymFL-pM',
    appId: '1:1051279993075:android:450a782451f583bfc8af86',
    messagingSenderId: '1051279993075',
    projectId: 'expensedaily-3582e',
    storageBucket: 'expensedaily-3582e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYsnr6NGtFnqvE4n7QSe2A-UcyvvBSKiw',
    appId: '1:1051279993075:ios:822fb53681bab545c8af86',
    messagingSenderId: '1051279993075',
    projectId: 'expensedaily-3582e',
    storageBucket: 'expensedaily-3582e.firebasestorage.app',
    iosBundleId: 'com.example.expenseDaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYsnr6NGtFnqvE4n7QSe2A-UcyvvBSKiw',
    appId: '1:1051279993075:ios:822fb53681bab545c8af86',
    messagingSenderId: '1051279993075',
    projectId: 'expensedaily-3582e',
    storageBucket: 'expensedaily-3582e.firebasestorage.app',
    iosBundleId: 'com.example.expenseDaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_M8VyK_4u0i-gRKx6l96za1XBp2cJzPk',
    appId: '1:1051279993075:web:0485afaed24a71bdc8af86',
    messagingSenderId: '1051279993075',
    projectId: 'expensedaily-3582e',
    authDomain: 'expensedaily-3582e.firebaseapp.com',
    storageBucket: 'expensedaily-3582e.firebasestorage.app',
    measurementId: 'G-MJ2VDDKQYM',
  );
}
